name: WSMSA-front
services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile.dev
    env_file:
      - ./node/.env.local
    volumes:
      - type: bind
        source: ../
        target: /schedule
      - type: volume
        source: node_modules
        target: /schedule/node_modules
    ports:
      - '3000:3000'
    networks:
      - schedule-network
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

volumes:
  node_modules:
networks:
  schedule-network:
