server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: root
    password: root
  sql:
    init:
      mode: always
      continue-on-error: false
      schema-locations:
        - classpath:schema/*.sql
      data-locations:
        - classpath:data/*.sql
logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
mybatis:
  mapper-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml
