services:
  java:
    container_name: java
    build:
      context: ./java
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ../
        target: /schedule
      - type: volume
        source: gradle-Work-Schedule-Management-and-Sharing-App
        target: /root/.gradle
    depends_on:
      - postgres
    networks:
      - schedule-network
    tty: true
  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: schedule_dbs
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: pgdata-Work-Schedule-Management-and-Sharing-App
        target: /var/lib/postgresql
    networks:
      - schedule-network
volumes:
  gradle-Work-Schedule-Management-and-Sharing-App:
  pgdata-Work-Schedule-Management-and-Sharing-App:
networks:
  schedule-network: